name: Build and deploy on push

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and deploy
        uses: zbrox/zola-deploy-action@vX.Y.Z
        env:
          TOKEN: ${{ secrets.TOKEN }}
